config/routes.rb
UrlShortener::Application.routes.draw do
  resources :urls do
    collection do
    end
  end

  get ':id' => 'urls#redirect'

  root 'urls#new'

end

app/models/url.rb
class Url < ActiveRecord::Base
  validates :href, format: { with: /[a-zA-Z]+:\/\/.*/, message: 'Invalid URI' },
                   presence: true
  validates :alias, format: { with: /[a-zA-Z0-9]*/ },
                    uniqueness: true,
                    presence: true
  validates :views, numericality: { only_integer: true }

  def alias_url
    #root_url + self.alias
    self.alias
  end

  def to_param
    self.alias
  end

  before_validation do
    self.alias.chomp!
    if self.alias.empty?
      # generate one
      self.custom = false
      self.alias = loop do
        str = generate_random_string
        break str unless Url.exists? alias: str
      end
    elsif self.alias_changed?
      self.custom = true
    end
  end

  before_save do
    if self.alias_changed?
      self.views = 0
    end
  end

  # generate a random string
  def generate_random_string(size = 5)
    charset = ('a'..'z').to_a + (0..9).to_a
    (0...size).map { charset[rand(charset.size)] }.join
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :set_url, only: [:edit, :update, :destroy, :redirect]

  # redirection
  def redirect
    if @url
      # increment view count
      @url.update(views: @url.views + 1)
      redirect_to @url.href, status: 301
    else
      index
      redirect_to Url, notice: params[:id].to_s + ' does not exist'
    end
  end

  # GET /urls
  # GET /urls.json
  def index
    @urls = Url.all
  end

  # GET /urls/new
  def new
    @url = Url.new
  end

  # GET /urls/1/edit
  def edit
  end

  def show
    redirect_to Url, notice: "URL updated!"
  end

  # POST /urls
  # POST /urls.json
  def create
    @url = Url.new(url_params)

    # if alias is left blank, then we should reuse the alias if one is already created
    if @url.alias.chomp.empty?
      result = Url.find_by href: @url.href
      if not result.nil?
        @url = result
        redirect_to @url, notice: 'One is already created'
        return
      end
    end

    if @url.save
      redirect_to @url, success: 'URL was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /urls/1
  def update
    if @url.update(url_params)
      redirect_to @url, success: 'URL was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /urls/1
  # DELETE /urls/1.json
  def destroy
    if @url.destroy
      redirect_to Url, notice: 'Url destroyed' #urls_url
    else
      redirect_to Url, notice: 'Error in destroy'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_url
      @url = Url.find_by(alias: params['id'])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def url_params
      params.require(:url).permit(:href, :alias, :views, :sticky)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>wchen.me url shortener</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link rel='stylesheet' href='//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css' />
  <script src='//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js'></script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/urls/_form.html.erb
<%= form_for(@url, html: {role: 'form'}, class: 'form-horizontal') do |f| %>
  <% if @url.errors.any? %>
    <div class='alert alert-danger'>
      <h2><%= pluralize(@url.errors.count, "error") %> prohibited this url from being saved:</h2>

      <ul>
      <% @url.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <style>
    .underlined-control, .underlined-control:focus {
      border: none;
      box-shadow: 0 0;
      -webkit-box-shadow: 0 0;
      border-bottom: 1px solid black;
    }
  </style>

  <div class="form-group">
    <%= f.label :href, "Original link", class: 'col-md-2 control-label' %>
    <div class="col-md-10">
      <%= f.text_field :href, type: 'url', class: 'form-control underlined-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :alias, "Custom alias", class: 'col-md-2 control-label'  %><br>
    <div class="col-md-10">
      <%= root_url %>
      <%= f.text_field :alias, class: 'form-control underlined-control', style: "display: inline; width: initial", size: 12 %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :views, class: 'col-md-2 control-label' %><br>
    <div class="col-md-10">
      <%= f.number_field :views, disabled: true, type: 'number', class: 'form-control', style: 'width: initial', size: 2 %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :sticky, class: 'col-md-2 control-label' %><br>
    <div class="col-md-10">
      <%= f.check_box :sticky, class: 'form-control' %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit("Update", class: 'btn btn-default btn-lg') %>
  </div>
<% end %>

app/views/urls/edit.html.erb
<div class="jumbotron">
  <h1>Editing url</h1>
</div>

<%= render 'form' %>

<div class="row">
  <div class="col-md-12">
    <%= link_to 'Back', urls_path %>
  </div>
</div>

app/views/urls/index.html.erb
<div class="jumbotron">
  <h1>Listing urls</h1>
</div>

<% if defined? success and success %>
  <div class="alert alert-success"><%= success %></div>
<% end %>
<% if defined? notice and notice %>
  <div class="alert alert-warning"><%= notice %></div>
<% end %>
<% if defined? error and error %>
  <div class="alert alert-danger"><%= error %></div>
<% end %>

<p>
  <%= link_to 'New Url', new_url_path, class: 'btn btn-primary', role: 'button' %>
</p>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Original link</th>
      <th>Shortened link</th>
      <th>View count</th>
      <th>Custom</th>
      <th>Admin actions</th>
    </tr>
  </thead>

  <tbody>
    <% @urls.each do |url| %>
      <tr>
        <td><%= link_to url.href, url.href %></td>
        <td><%= link_to url.alias, root_url + url.alias %></td>
        <td><%= url.views %></td>
        <td><%= url.custom %></td>
        <td><%= link_to 'Edit', edit_url_path(url) %>
            <% unless url.sticky? %> | <%= link_to 'Destroy', url, method: :delete, data: { confirm: 'Are you sure?' } %> <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/urls/new.html.erb
<h1>New url</h1>

<%= render 'form' %>

<%= link_to 'Back', urls_path %>

app/views/urls/splash.html.erb
<div class="row">
  <div class='col-md-12'>
    <div style='margin: 0 auto; width: 500px'>
      <%= form_for(@url, html: {role: 'form'}) do |f| %>
        <% if @url.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@url.errors.count, "error") %> prohibited this url from being saved:</h2>

            <ul>
            <% @url.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.label(:href, "Link to shorten") %>
          <%= f.text_field(:href, class: 'form-control', placeholder: 'http://www.example.com', type: 'url') %>
        </div>
        <div class="form-group">
          <%= f.label(:alias, "Custom alias (optional)") %> <br>
          <%= root_url %>
          <%= f.text_field(:alias, class: 'form-control', style: 'width: 100px; display: inline') %>
          &nbsp; <%= f.check_box(:sticky) %> Sticky?
        </div>
        <div class="actions">
          <%= f.submit("Shorten URL", class: 'btn btn-default') %>
        </div>
      <% end %>
    </div>
  </div>
</div>